import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import Navbar from '@/components/navbar/Navbar'
import { Providers } from '@/app/providers'
import 'primeicons/primeicons.css'
import 'primereact/resources/themes/saga-blue/theme.css'
import '../styles/globals.css'
const inter = Inter({ subsets: ['latin'] })

import { dir } from 'i18next'
import { languages } from './i18n/settings'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Nueva arquitectura',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { lng },
}: RootLayoutProps): React.ReactElement {
  return (
    <html className="dark" lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
