import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import Navbar from '@/components/navbar/Navbar'
import 'primeicons/primeicons.css'
import 'primereact/resources/themes/saga-blue/theme.css'
import '../../styles/globals.css'
import { Providers } from '@/app/[locale]/providers'
import { NextIntlClientProvider, useMessages } from 'next-intl'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nueva arquitectura',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
  params: { locale: 'en' | 'es' }
}

const RootLayout: React.FC<Props> = ({ children, params: { locale } }) => {
  const messages = useMessages()

  return (
    <html lang={locale} className="dark">
      <NextIntlClientProvider messages={messages}>
        <body className={inter.className}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </NextIntlClientProvider>
    </html>
  )
}

export default RootLayout
